### PR TITLE
Improve and consolidate documentation structure

### PR DESCRIPTION
**Pull request by fxthomas**
I went a bit overboard with this, sorry for the mix-mash of unrelated changes. The PR does a few things to improve the docs:

* Developer: Consolidates 2 pages about performance tests that were not linked to anywhere
* Developer: Adds a page about Maven usage following our discussion in https://github.com/airsonic/airsonic/issues/1240
* Proxy: Consolidates all proxy setup instructions
* Spelling fixes, as well as fixes for correctly showing the ToC on some pages

The sister PR in the website is https://github.com/airsonic/airsonic.github.io/pull/39.

### CODE REVIEW

**Comment by fxthomas** [comment]
...I really did the very thing I don't like, mixing multiple unrelated things in the same PR. Let me know if you want to me to split this.

**Comment by tesshucom** [comment]
I haven't got the time yet.
By the way, CHANGELOG.md may not have been updated...
I overlooked it.

**Comment by fxthomas** [comment]
I updated the changelog file while doing 10.6.1 (it's not actually part of the website I think), and I just updated the stable version in 1c808d8c0cdc42cb55b149a09815c73636fedb9d.

**Comment by eharris** [comment]
Thanks a lot for this @fxthomas!  Nice improvements!

**Pull request merged**
